# FastAgent Configuration File

# Default Model Configuration:
# 
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4o-mini, gpt-4o, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku". 
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.

default_model: openai.o3-mini.high

# Logging and Console Configuration:
logger:
    level: "debug"  # Enable debug logging to see more details about MCP server issues
    type: "console"  
    
    # Switch the progress display on or off
    progress_display: true

    # Show chat User/Assistant messages on the console
    show_chat: true
    # Show tool calls on the console
    show_tools: true
    # Truncate long tool responses on the console 
    truncate_tools: true

# MCP Servers - Updated with correct module paths and settings for recent MCP versions
mcp_servers:
    fetch:
        # Using direct module reference for maximum compatibility
        command: "python3"
        args: ["-m", "mcp.server.fetch"]
        restart_on_error: true
        restart_limit: 3
        timeout: 30
    filesystem:
        # Using direct module reference for filesystem with explicit path to project root
        command: "python3" 
        args: ["-m", "mcp.server.filesystem", "."]
        restart_on_error: true
        restart_limit: 3
        timeout: 30
