# FastAgent Configuration File

# Default Model Configuration:
# 
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4o-mini, gpt-4o, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku". 
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.

default_model: openai.o3-mini.high

# Logging and Console Configuration:
logger:
    level: "debug"  # Enable debug logging to see more details about MCP server issues
    type: "console"  
    
    # Switch the progress display on or off
    progress_display: true

    # Show chat User/Assistant messages on the console
    show_chat: true
    # Show tool calls on the console
    show_tools: true
    # Truncate long tool responses on the console 
    truncate_tools: true

# MCP Servers with exact key names matching agent server references
mcp_servers:
    # The exact server name must match what's used in @fast.agent(servers=["fetch", "filesystem"])
    "fetch":
        server_type: "subprocess"
        command: "python3"
        args: ["-m", "mcp.server.fetch"]
        timeout: 45  # Increased timeout for network operations
        # Add retry settings to improve reliability
        max_restarts: 3
        restart_delay: 2
    "filesystem":
        server_type: "subprocess"
        command: "python3" 
        args: ["-m", "mcp.server.filesystem", "/opt/render/project/src"]
        timeout: 30
        # Add retry settings to improve reliability
        max_restarts: 3
        restart_delay: 2

# Fallback responses when MCP servers are unavailable
fallbacks:
    enabled: true
    responses:
        default: "I'm sorry, I couldn't access that information right now."
        filesystem: "I couldn't access the bakery schedule at the moment."
        fetch: "I couldn't check the menu right now."
