services:
  - type: web
    name: bakery-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python3 bakery_api_with_mcp.py
    plan: free
    healthCheckPath: /status
    # Keep the service running even if health check fails initially
    healthCheckTimeout: 60
    # Disable auto-deploy to ensure manual control over deployments
    autoDeploy: false
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "True"
      - key: LOGLEVEL
        value: "debug" 