services:
  - type: web
    name: bakery-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bakery_api_simplified:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 