services:
  - type: web
    name: bakery-api
    env: python
    buildCommand: pip install fastapi uvicorn pydantic
    startCommand: python bakery_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 