services:
  - type: web
    name: bakery-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 