services:
  - type: web
    name: bakery-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python3 bakery_api_with_mcp.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 