services:
  - type: web
    name: bakery-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn bakery_api_simplified:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 