services:
  - type: web
    name: bakery-api
    env: python
    buildCommand: pip install fastapi==0.115.6 uvicorn==0.23.2 pydantic==2.10.4
    startCommand: python3 /opt/render/project/src/bakery_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 