services:
  - type: web
    name: bakery-api
    env: python
    buildCommand: pip install fastapi==0.115.6 uvicorn==0.23.2
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 