services:
  - type: web
    name: bakery-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /status
    # Wait for 90 seconds before considering the deployment successful
    initialDeployHook: sleep 90
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED 
        value: 1 